image: "kroniak/ssh-client"

stages:
  - develop

.deploy:
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -tt yasuo@$HOST "cd backend/$SRC && git checkout $BRANCH && git pull && make compose_prod"

deploy:develop:
  extends: .deploy
  stage: develop
  variables:
    SRC: cr-product
    BRANCH: develop
  only:
    - develop
