version: '3.7'
services:
  cr-product:
    image: "cr-product:1.0.0"
    container_name: cr-product
    hostname: cr-product
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - ENV_DEV=${ENV_DEV}
      - PORT=${PORT}
      - RB_HOST=${RB_HOST}
      - RB_PORT=${RB_PORT}
      - RB_USER=${RB_USER}
      - RB_PASS=${RB_PASS}
      - RB_PORT_UI=${RB_PORT_UI}
      - QUEUE_NAME=${QUEUE_NAME}
      - NUMBER_WORKER=${NUMBER_WORKER}
    ports:
      - 8084:8084
    networks:
      - cr-networks

networks:
  cr-networks:
    external: 
      name: cr-networks